### ISSUE TITLE
tcp connected, but no http response?

### ISSUE THREAD

**Issue by zhuangya** [yorkie/serve#6]
hey Yorkie

i cloned this repo, build the binary myself.

but when i run `dest/serve`, there is no http response.

below is the traffic i captured.

http://7xl8jh.com1.z0.glb.clouddn.com/serve-dump.pcap

and here is the preview:

![image](https://cloud.githubusercontent.com/assets/499038/11070140/f4e60f0a-8814-11e5-81d8-56a6de91f2a3.png)

---

not sure what's wrong here, it's really strange..

**Comment by yorkie** [comment]
No http response? this is used for serving static files, do you try with files?

**Comment by zhuangya** [comment]
there is a `public` directory, in the `public` directory, there is a file `index.html`

**Comment by yorkie** [comment]
And do you access to index.html, and all of its requests get normal responses?

**Comment by zhuangya** [comment]
no nothing.

just hang
